import jsPDF from "jspdf";

export default async function generatePDF({
  setIsPdfLoading,
  selectedCandidate,
  technicalRating,
  technicalSummary,
  softSkillRating,
  softSkillSummary,
  codingRating,
  codingSummary,
}) {
  console.log("generating pdf");
  console.log(selectedCandidate);

  try {
    setIsPdfLoading(true);
    const pdf = new jsPDF("landscape", "px", "a4"); // Use A4 size in millimeters
    const contentWidth = 210; // A4 Page width in mm
    const contentHeight = 297; // A4 Page height in mm

    // Use the actual DOM element and apply scaling
    const htmlContent = `
    <div style="
      font-family: 'Helvetica', sans-serif; 
      color: #333; 
      padding: 20px; 
      background: #f9f9f9; 
      border-radius: 12px; 
      box-shadow: 0 4px 8px rgba(0,0,0,0.1); 
      width: 600px;
    ">
      <!-- Header -->
      <div style="
        text-align: center; 
        background: linear-gradient(90deg, #007BFF, #00D4FF); 
        color: #fff; 
        padding: 20px 10px; 
        border-radius: 12px 12px 0 0;
      ">
        <h1 style="font-size: 28px; font-weight: bold; margin: 0;">
          Candidate Report
        </h1>
        <p style="font-size: 16px; margin-top: 5px;">
          ${selectedCandidate ? `${selectedCandidate.customer.name}` : "Candidate Name"}
        </p>
      </div>
       <!-- Technical Section -->
        <div style="margin-bottom: 20px;">
          <h2 style="
            font-size: 20px;
            color: #444;
            margin-bottom: 10px;
            border-bottom: 1px solid #ddd;
            padding-bottom: 5px;
          ">
            Technical Skills
          </h2>
          <p style="
            font-size: 18px;
            font-weight: bold;
            color: #007BFF;
          ">
            Rating: ${technicalRating}/10
          </p>
          <p style="font-size: 14px; color: #555; line-height: 1.6;">
            ${technicalSummary}
          </p>
        </div>
     
<!-- Soft Skills Section -->
        <div style="margin-bottom: 20px;">
          <h2 style="
            font-size: 20px;
            color: #444;
            margin-bottom: 10px;
            border-bottom: 1px solid #ddd;
            padding-bottom: 5px;
          ">
            Soft Skills
          </h2>
          <p style="
            font-size: 18px;
            font-weight: bold;
            color: #007BFF;
          ">
            Rating: ${softSkillRating}/10
          </p>
          <p style="font-size: 14px; color: #555; line-height: 1.6;">
            ${softSkillSummary}
          </p>
        </div>

        <!-- Coding Section -->
        <div style="margin-bottom: 20px;">
          <h2 style="
            font-size: 20px;
            color: #444;
            margin-bottom: 10px;
            border-bottom: 1px solid #ddd;
            padding-bottom: 5px;
          ">
            Coding Skills
          </h2>
          <p style="
            font-size: 18px;
            font-weight: bold;
            color: #007BFF;
          ">
            Rating: ${codingRating}/10
          </p>
          <p style="font-size: 14px; color: #555; line-height: 1.6;">
            ${codingSummary}
          </p>
        </div>

        <!-- Footer -->
        <div style="
          text-align: center;
          padding-top: 10px;
          border-top: 2px solid #007BFF;
          margin-top: 20px;
        ">
          <p style="
            font-size: 12px;
            color: #888;
          ">
            Generated on ${new Date().toLocaleDateString()} | Generated by Co-Ventech
          </p>
        </div>
      </div>
    `;

    pdf.html(htmlContent, {
      callback: function (pdf) {
        pdf.save(
          selectedCandidate
            ? `${selectedCandidate?.customer?.name}'s-report.pdf`
            : "candidate-report.pdf"
        );
      },
      x: 10, // Left margin
      y: 10, // Top margin
      autoPaging: true,
      margin: 10,
    });

    setIsPdfLoading(false);
  } catch (error) {
    console.error("Error generating PDF:", error);
  } finally {
    setIsPdfLoading(false);
  }
}
        
